version: '3.8'

x-common-variables: &common-variables
  SQL_HOST: "sql"
  SQL_DATABASE: "Zombo"
  SQL_USER: "SQL_USER"
  SQL_PASSWORD: "SQL_PASS"
  MYSQL_USER: "SQL_USER"
  MYSQL_PASSWORD: "SQL_PASS"
  MYSQL_DATABASE: "Zombo"

services:
  frontend:
    image: chrisashtear/zomboid-reporter-frontend:latest
    restart: always
  nginx:
    depends_on:
      - reporter-api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  reporter:
    image: chrisashtear/zomboid-reporter:latest
    restart: always
    environment:
      <<: *common-variables
      ZOMBOID_SERVER_NAME: "pz"
    volumes:
      - './z/server-data:/var/www/html/sv'
  reporter-api:
    image: chrisashtear/zomboid-reporter-backend:latest
    restart: always
    depends_on:
      - sql
    environment:
      <<: *common-variables
  discord:
    image: chrisashtear/zomboid-discobot:latest
    depends_on:
      - reporter-api
    restart: always
    environment:
      CLIENT_TOKEN: "TOKEN"
      API_HOST: "reporter-api"
      API_PORT: 3001
  sql:
    image: mysql:latest
    command: --init-file /data/application/init.sql
    restart: always
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "SQL_ROOT_PASS"
      <<: *common-variables
  adminer:
    image: adminer
    restart: always
    ports:
      - 899:8080
  project-zomboid:
    image: afey/zomboid
    restart: unless-stopped
    environment:
      SERVER_NAME: "PZ"
      ADMIN_PASSWORD: "ADMIN_PASS"
      SERVER_BRANCH: ""
      RCON_PASSWORD: "RCON"
      SERVER_PUBLIC_NAME: "Server Name"
      SERVER_PUBLIC_DESC: ""
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262-16302:16262-16302"
      - "27015:27015"
    volumes:
      - './z/server-data:/server-data'
